magic_castle::site::tags:
  haproxy:
    - haproxy
  edx:
    - restic
    - cqedu
    - tutor
    - cron

lookup_options:
  tutor::config:
    merge: hash
  tutor::openedx_extra_pip_requirements:
    merge: deep
  tutor::registration_email_patterns_allowed:
    merge: deep
  tutor::plugins:
    merge: deep
  tutor::env_patches:
    merge: deep

tutor::version: '18.1.4'

profile::reverse_proxy::subdomains:
  edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  preview.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  studio.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  apps.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  data.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  jupyter: "https://127.0.0.1:8000"
profile::reverse_proxy::main2sub_redir: "edx"

tutor::admin_email: "noreply@calculquebec.ca"
tutor::admin_password: "%{alias('edx_admin_password')}"

tutor::config:
  LANGUAGE_CODE: "fr"
  PLATFORM_NAME: "EdX Calcul Québec"
  CONTACT_EMAIL: "noreply@calculquebec.ca"
  LMS_HOST: "edx.%{lookup('terraform.data.domain_name')}"
  CMS_HOST: "studio.edx.%{lookup('terraform.data.domain_name')}"
  PREVIEW_LMS_HOST: "preview.edx.%{lookup('terraform.data.domain_name')}"
  ENABLE_WEB_PROXY: "false"
  CADDY_HTTP_PORT: "0.0.0.0:80"
  ENABLE_HTTPS: "true"
  MYSQL_ROOT_PASSWORD: "%{alias('mysql_root_password')}"
  BACKUP_MYSQL_DATABASES: "['openedx']"
  CAIRN_AUTH_ROLES_SYNC_AT_LOGIN: "true"
  INDIGO_WELCOME_MESSAGE: "Votre référence en recherche numérique"

tutor::env_patches:
  common-env-features:
    - "'ENABLE_THIRD_PARTY_AUTH': True"
    - "'ENABLE_COMBINED_LOGIN_REGISTRATION': True"
    - "'SHOW_REGISTRATION_LINKS': False"
    - "'CERTIFICATES_HTML_VIEW': True"
  openedx-lms-common-settings:
    - "AUTHENTICATION_BACKENDS += ['social_core.backends.open_id_connect.OpenIdConnectAuth']"
  openedx-auth:
    - "'SOCIAL_AUTH_OIDC_OIDC_ENDPOINT': 'https://cilogon.org/'"
    - "'SOCIAL_AUTH_OIDC_KEY': 'cilogon:/client_id/4b76e902d5e4d192d630bcfc3823e88f'"
    - "'SOCIAL_AUTH_OIDC_SECRET': '%{lookup('oidc_secret')}'"
    - "'SOCIAL_AUTH_OAUTH_SECRETS': { 'oidc': '%{lookup('oidc_secret')}'}"
  mfe-lms-production-settings:
    - "MFE_CONFIG['ALLOW_PUBLIC_ACCOUNT_CREATION'] = True"
    - "MFE_CONFIG['SHOW_REGISTRATION_LINKS'] = False"

tutor::openedx_extra_pip_requirements:
  - 'jupyter-xblock==17.0.0'
  - 'h5p-xblock==0.2.15'

tutor::plugins:
  cairn:
    reboot_on_change: true
  indigo:
    source: "git+https://github.com/calculquebec/tutor-indigo@%{lookup('theme_hash')}"
    image: "openedx"
    rebuild_image_on_content_change: true

tutor::registration_email_patterns_allowed:
  - "(^\\w+)@.*acadiau.ca$"
  - "(^\\w+)@.*alliancecan.ca$"
  - "(^\\w+)@.*athabascau.ca$"
  - "(^\\w+)@.*baycrest.org$"
  - "(^\\w+)@.*bccrc.ca$"
  - "(^\\w+)@.*bcgsc.ca$"
  - "(^\\w+)@.*bcit.ca$"
  - "(^\\w+)@.*bdeb.qc.ca$"
  - "(^\\w+)@.*brandonu.ca$"
  - "(^\\w+)@.*brebeuf.qc.ca$"
  - "(^\\w+)@.*brocku.ca$"
  - "(^\\w+)@.*calculquebec.ca$"
  - "(^\\w+)@.*camh.ca$"
  - "(^\\w+)@.*capilanou.ca$"
  - "(^\\w+)@.*carleton.ca$"
  - "(^\\w+)@.*cbu.ca$"
  - "(^\\w+)@.*cegepjonquiere.ca$"
  - "(^\\w+)@.*cegeplevis.ca$"
  - "(^\\w+)@.*cegepmontpetit.ca$"
  - "(^\\w+)@.*cegepoutaouais.qc.ca$"
  - "(^\\w+)@.*cegeprdl.ca$"
  - "(^\\w+)@.*cgodin.qc.ca$"
  - "(^\\w+)@.*cgq.qc.ca$"
  - "(^\\w+)@.*cmaisonneuve.qc.ca$"
  - "(^\\w+)@.*cmrsj-rmcsj.ca$"
  - "(^\\w+)@.*cna.nl.ca$"
  - "(^\\w+)@.*concordia.ab.ca$"
  - "(^\\w+)@.*concordia.ca$"
  - "(^\\w+)@.*conestogac.on.ca$"
  - "(^\\w+)@.*cshawi.ca$"
  - "(^\\w+)@.*cstj.qc.ca$"
  - "(^\\w+)@.*cvm.qc.ca$"
  - "(^\\w+)@.*dal.ca$"
  - "(^\\w+)@.*dawsoncollege.qc.ca$"
  - "(^\\w+)@.*dcmail.ca$"
  - "(^\\w+)@.*dfo-mpo.gc.ca$"
  - "(^\\w+)@.*douglascollege.ca$"
  - "(^\\w+)@.*etsmtl.ca$"
  - "(^\\w+)@.*fanshaweonline.ca$"
  - "(^\\w+)@.*georgebrown.ca$"
  - "(^\\w+)@.*hec.ca$"
  - "(^\\w+)@.*imar.ca$"
  - "(^\\w+)@.*kpu.ca$"
  - "(^\\w+)@.*lakeheadu.ca$"
  - "(^\\w+)@.*langara.ca$"
  - "(^\\w+)@.*laurentian.ca$"
  - "(^\\w+)@.*lunenfeld.ca$"
  - "(^\\w+)@.*macewan.ca$"
  - "(^\\w+)@.*marianopolis.edu$"
  - "(^\\w+)@.*mcgill.ca$"
  - "(^\\w+)@.*mcmaster.ca$"
  - "(^\\w+)@.*mhc.ab.ca$"
  - "(^\\w+)@.*msvu.ca$"
  - "(^\\w+)@.*mta.ca$"
  - "(^\\w+)@.*mtroyal.ca$"
  - "(^\\w+)@.*mun.ca$"
  - "(^\\w+)@.*mylaurier.ca$"
  - "(^\\w+)@.*myokanagan.bc.ca$"
  - "(^\\w+)@.*myseneca.ca$"
  - "(^\\w+)@.*mytwu.ca$"
  - "(^\\w+)@.*myumanitoba.ca$"
  - "(^\\w+)@.*nait.ca$"
  - "(^\\w+)@.*nic.bc.ca$"
  - "(^\\w+)@.*nipissingu.ca$"
  - "(^\\w+)@.*nscc.ca$"
  - "(^\\w+)@.*ocadu.ca$"
  - "(^\\w+)@.*ohri.ca$"
  - "(^\\w+)@.*oicr.on.ca$"
  - "(^\\w+)@.*ouranos.ca$"
  - "(^\\w+)@.*perimeterinstitute.ca$"
  - "(^\\w+)@.*polymtl.ca$"
  - "(^\\w+)@.*queensu.ca$"
  - "(^\\w+)@.*rdpolytech.ca$"
  - "(^\\w+)@.*rmc.ca$"
  - "(^\\w+)@.*rrc.ca$"
  - "(^\\w+)@.*ryerson.ca$"
  - "(^\\w+)@.*sait.ca$"
  - "(^\\w+)@.*selkirk.ca$"
  - "(^\\w+)@.*sfu.ca$"
  - "(^\\w+)@.*sheridancollege.ca$"
  - "(^\\w+)@.*sickkids.ca$"
  - "(^\\w+)@.*smu.ca$"
  - "(^\\w+)@.*snolab.ca$"
  - "(^\\w+)@.*ssss.gouv.qc.ca$"
  - "(^\\w+)@.*stfx.ca$"
  - "(^\\w+)@.*teluq.ca$"
  - "(^\\w+)@.*trentu.ca$"
  - "(^\\w+)@.*triumf.ca$"
  - "(^\\w+)@.*tru.ca$"
  - "(^\\w+)@.*ualberta.ca$"
  - "(^\\w+)@.*ubc.ca$"
  - "(^\\w+)@.*ubishops.ca$"
  - "(^\\w+)@.*ucalgary.ca$"
  - "(^\\w+)@.*ufv.ca$"
  - "(^\\w+)@.*ulaval.ca$"
  - "(^\\w+)@.*uleth.ca$"
  - "(^\\w+)@.*umoncton.ca$"
  - "(^\\w+)@.*umontreal.ca$"
  - "(^\\w+)@.*unb.ca$"
  - "(^\\w+)@.*unbc.ca$"
  - "(^\\w+)@.*uoguelph.ca$"
  - "(^\\w+)@.*uoit.ca$"
  - "(^\\w+)@.*uottawa.ca$"
  - "(^\\w+)@.*upei.ca$"
  - "(^\\w+)@.*uqac.ca$"
  - "(^\\w+)@.*uqam.ca$"
  - "(^\\w+)@.*uqar.ca$"
  - "(^\\w+)@.*uqo.ca$"
  - "(^\\w+)@.*uqtr.ca$"
  - "(^\\w+)@.*uregina.ca$"
  - "(^\\w+)@.*usainteanne.ca$"
  - "(^\\w+)@.*usask.ca$"
  - "(^\\w+)@.*usherbrooke.ca$"
  - "(^\\w+)@.*ustboniface.ca$"
  - "(^\\w+)@.*utoronto.ca$"
  - "(^\\w+)@.*uvic.ca$"
  - "(^\\w+)@.*uwaterloo.ca$"
  - "(^\\w+)@.*uwindsor.ca$"
  - "(^\\w+)@.*uwinnipeg.ca$"
  - "(^\\w+)@.*uwo.ca$"
  - "(^\\w+)@.*vaniercollege.qc.ca$"
  - "(^\\w+)@.*vcc.ca$"
  - "(^\\w+)@.*vectorinstitute.ai$"
  - "(^\\w+)@.*viu.ca$"
  - "(^\\w+)@.*yorku.ca$"
  - "(^\\w+)@.*yukoncollege.yk.ca$"


prometheus::global_config:
    scrape_interval: '1m'
    scrape_timeout: '1m'
    external_labels:
        cluster: "%{alias('cluster_name')}"
        cloud: "%{alias('cloud_name')}"
        team: 'calculquebec'
        purpose: "formation"
        replica: '1'

prometheus::remote_write_configs:
    - url: 'https://thanos-receive.dant.computecanada.ca/api/v1/receive'
      basic_auth:
          username: 'cqformation'
          password: "%{alias('prometheus_password')}"
