magic_castle::site::tags:
  haproxy:
    - haproxy
  edx:
    - tutor
    - cron
    - restic

profile::reverse_proxy::subdomains:
  edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  preview.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  studio.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  apps.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  jupyter: "https://127.0.0.1:8000"
profile::reverse_proxy::main2sub_redir: "edx"

tutor::admin_email: "noreply@calculquebec.ca"
tutor::admin_password: "%{alias('edx_admin_password')}"

tutor::config:
  - ["LANGUAGE_CODE", "fr"]
  - ["PLATFORM_NAME", "EdX Calcul Québec"]
  - ["CONTACT_EMAIL", "noreply@calculquebec.ca"]
  - ["LMS_HOST", "edx.%{lookup('terraform.data.domain_name')}"]
  - ["CMS_HOST", "studio.edx.%{lookup('terraform.data.domain_name')}"]
  - ["PREVIEW_LMS_HOST", "preview.edx.%{lookup('terraform.data.domain_name')}"]
  - ["ENABLE_WEB_PROXY", "false"]
  - ["CADDY_HTTP_PORT", "0.0.0.0:80"]
  - ["ENABLE_HTTPS", "true"]
  - ["MYSQL_ROOT_PASSWORD", "%{alias('mysql_root_password')}"]
  - ["BACKUP_MYSQL_DATABASES", "['openedx']"]

prometheus::global_config:
    scrape_interval: '1m'
    scrape_timeout: '1m'
    external_labels:
        cluster: "%{alias('cluster_name')}"
        cloud: "%{alias('cloud_name')}"
        team: 'calculquebec'
        purpose: "formation"
        replica: '1'

prometheus::remote_write_configs:
    - url: 'https://thanos-receive.dant.computecanada.ca/api/v1/receive'
      basic_auth:
          username: 'cqformation'
          password: "%{alias('prometheus_password')}"
