magic_castle::site::tags:
  haproxy:
    - haproxy
  edx:
    - restic
    - cqedu
    - tutor
    - cron

lookup_options:
  tutor::config:
    merge: hash
  tutor::openedx_extra_pip_requirements:
    merge: deep
  tutor::registration_email_patterns_allowed:
    merge: deep
  tutor::plugins:
    merge: deep
  tutor::env_patches:
    merge: deep
  cron::job:
    merge: hash

profile::reverse_proxy::subdomains:
  edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  preview.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  studio.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  apps.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  data.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  jupyter: "https://127.0.0.1:8000"
profile::reverse_proxy::main2sub_redir: "edx"

prometheus::global_config:
    scrape_interval: '1m'
    scrape_timeout: '1m'
    external_labels:
        cluster: "%{alias('cluster_name')}"
        cloud: "%{alias('cloud_name')}"
        team: 'calculquebec'
        purpose: "formation"
        replica: '1'

prometheus::remote_write_configs:
    - url: 'https://thanos-receive.dant.computecanada.ca/api/v1/receive'
      basic_auth:
          username: 'cqformation'
          password: "%{alias('prometheus_password')}"
