magic_castle::site::tags:
  mgmt_extra:
    - cqedu::mgmt
  edx:
    - restic
    - cqedu
    - tutor
    - cron
    - profile::mail
  internal_login:
    - motd
    - profile::slurm::submitter
    - profile::ssh::hostbased_auth::client
    - profile::ssh::hostbased_auth::server
    - profile::nfs
    - profile::software_stack
  proxy:
    - profile::reverse_proxy
    - profile::prometheus::caddy_exporter
  jupyterhub:
    - profile::jupyterhub::hub
    - profile::jupyterhub::hub::keytab

lookup_options:
  tutor::config:
    merge: hash
  tutor::openedx_extra_pip_requirements:
    merge: deep
  tutor::registration_email_patterns_allowed:
    merge: deep
  tutor::plugins:
    merge: deep
  tutor::env_patches:
    merge: deep
  cron::job:
    merge: hash

lookup_options:
  profile::users::ldap::groups:
    merge: first
profile::users::ldap::groups:
  'def-sponsor00':
    automember: true
    hbac_rules: ["internal_login:sshd", 'node:sshd', 'proxy:jupyterhub-login']


profile::reverse_proxy::subdomains:
  edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  preview.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  studio.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  apps.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  data.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  superset.edx: "http://edx1.int.%{lookup('terraform.data.domain_name')}"
  jupyter: "https://jupyter1.int.%{lookup('terraform.data.domain_name')}:8081" #127.0.0.1:8000"
profile::reverse_proxy::main2sub_redir: "edx"

prometheus::global_config:
    scrape_interval: '1m'
    scrape_timeout: '1m'
    external_labels:
        cluster: "%{alias('cluster_name')}"
        cloud: "%{alias('cloud_name')}"
        team: 'calculquebec'
        purpose: "formation"
        replica: '1'

prometheus::remote_write_configs:
    - url: 'https://thanos-receive.dant.computecanada.ca/api/v1/receive'
      basic_auth:
          username: 'cqformation'
          password: "%{alias('prometheus_password')}"

profile::slurm::base::slurm_version: '24.11'
profile::slurm::base::suspend_time: 900
profile::slurm::base::resume_timeout: 900
profile::slurm::base::suspend_rate: 80
profile::slurm::base::resume_rate: 80

profile::mail::dkim::private_key: "%{alias('dkim_key')}"
profile::nfs::server::enable_client_quotas: true

